# netlify.toml
[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  publish = "."
  functions = "netlify/functions"
  port = 8888
  autoLaunch = true

# --- Fix for iOS PWA Login (Reverse Proxy) ---
[[redirects]]
  from = "/__/auth/*"
  to = "https://interest-calculator-8d997.firebaseapp.com/__/auth/:splat"
  status = 200
  force = true
